/// Auto-generated from semantic witness description.
/// Source: semantic_kernel_canonical
/// Definition: ${DEF_TYPE}Definition
///
/// This file is generated by generate_canonical_mlir.sh,
/// not hand-authored.
///
/// Semantic Program:
///   Counter c1=${C1_INITIAL}, c2=${C2_INITIAL}
///   Transform c1: +3 (success, c1 → 8)
///   Transform c2: -12 (CONSTRAINT FAILURE, c2 unchanged at 10)
///   Transform c2: -2 (success, c2 → 8)
///   Observe c1 → 8, c2 → 8
///
/// Representation mapping:
///   Entity Instances → memref<1xi32> allocations
///   Constraints      → scf.if/else guards
///   Observations     → return values

module attributes {
  scr.provenance = {
    source = "generated_from_semantic_witness",
    definition = "CounterDefinition",
    generation_method = "template_expansion",
    semantic_source = "test_end_to_end_witness"
  },
  scr.entity_definition = {
    type_id = "Counter",
    value_schema = ["value"]
  },
  scr.entity_instance = [
    { entity_id = "c1", definition_type = "Counter", initial_value = 5 : i32 },
    { entity_id = "c2", definition_type = "Counter", initial_value = 10 : i32 }
  ],
  scr.relationship = {
    rel_id = "r1",
    kind = "LINKS",
    source = "c1",
    target = "c2"
  },
  scr.constraint = {
    kind = "non_negative",
    target_entity = "c1,c2",
    target_property = "value"
  },
  scr.context = {
    initial_step = 0 : index,
    label = "end-to-end-witness"
  }
} {
  func.func @end_to_end_witness() -> (i32, i32) attributes {
    scr.semantic_program = true
  } {
    // ---- c1 initial = 5 ----
    %c1_init = arith.constant 5 : i32
    %c1_state = memref.alloca() : memref<1xi32>
    %idx0 = arith.constant 0 : index
    memref.store %c1_init, %c1_state[%idx0] : memref<1xi32>

    // ---- c2 initial = 10 ----
    %c2_init = arith.constant 10 : i32
    %c2_state = memref.alloca() : memref<1xi32>
    memref.store %c2_init, %c2_state[%idx0] : memref<1xi32>

    // ---- Transform c1: +3 (success) ----
    %c3 = arith.constant 3 : i32
    %c1_v0 = memref.load %c1_state[%idx0] : memref<1xi32>
    %c1_v1 = arith.addi %c1_v0, %c3 : i32
    %c0 = arith.constant 0 : i32
    %cmp1 = arith.cmpi sge, %c1_v1, %c0 : i32
    scf.if %cmp1 {
      memref.store %c1_v1, %c1_state[%idx0] : memref<1xi32>
    } else {
      %c1_keep = memref.load %c1_state[%idx0] : memref<1xi32>
      memref.store %c1_keep, %c1_state[%idx0] : memref<1xi32>
    }

    // ---- Transform c2: -12 (CONSTRAINT FAILURE) ----
    %c_neg12 = arith.constant -12 : i32
    %c2_v0 = memref.load %c2_state[%idx0] : memref<1xi32>
    %c2_v_fail = arith.addi %c2_v0, %c_neg12 : i32
    %cmp_fail = arith.cmpi sge, %c2_v_fail, %c0 : i32
    scf.if %cmp_fail {
      memref.store %c2_v_fail, %c2_state[%idx0] : memref<1xi32>
    } else {
      // Constraint violated: c2 unchanged
      %c2_keep = memref.load %c2_state[%idx0] : memref<1xi32>
      memref.store %c2_keep, %c2_state[%idx0] : memref<1xi32>
    }

    // ---- Transform c2: -2 (success) ----
    %c_neg2 = arith.constant -2 : i32
    %c2_v1 = memref.load %c2_state[%idx0] : memref<1xi32>
    %c2_v2 = arith.addi %c2_v1, %c_neg2 : i32
    %cmp2 = arith.cmpi sge, %c2_v2, %c0 : i32
    scf.if %cmp2 {
      memref.store %c2_v2, %c2_state[%idx0] : memref<1xi32>
    } else {
      %c2_keep2 = memref.load %c2_state[%idx0] : memref<1xi32>
      memref.store %c2_keep2, %c2_state[%idx0] : memref<1xi32>
    }

    // ---- Observe c1 and c2 ----
    %r1 = memref.load %c1_state[%idx0] : memref<1xi32>
    %r2 = memref.load %c2_state[%idx0] : memref<1xi32>
    return %r1, %r2 : i32, i32
  }
}
