#!/usr/bin/env bash
# Generate canonical MLIR from semantic witness description.
#
# This script demonstrates that the canonical MLIR artifact is
# DERIVABLE from the semantic witness, not hand-authored.
#
# Workflow:
#   1. Structured semantic program description (input)
#   2. Template expansion → MLIR generation
#   3. Parse verification
#   4. Lower to LLVM (optional)
#   5. Execute and verify (optional)
#
# Usage:
#   ./generate_canonical_mlir.sh              # generate only
#   ./generate_canonical_mlir.sh --verify     # generate + parse
#   ./generate_canonical_mlir.sh --full       # generate + parse + lower + execute

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR"
VERIFY=false
FULL=false

for arg in "$@"; do
    case "$arg" in
        --verify) VERIFY=true ;;
        --full)   FULL=true ;;
        --help|-h)
            echo "Usage: $0 [--verify|--full]"
            echo "  (no flag)  Generate MLIR only"
            echo "  --verify   Generate + parse verification"
            echo "  --full     Generate + parse + lower + execute"
            exit 0
            ;;
    esac
done

# ============================================================
# Semantic Witness Description (structured input)
# ============================================================
# These variables define the semantic program.
# The MLIR is generated FROM these, not hand-authored.

DEF_TYPE="Counter"
DEF_PROPERTIES="value"
C1_ID="c1"
C1_TYPE="Counter"
C1_INITIAL=5
C2_ID="c2"
C2_TYPE="Counter"
C2_INITIAL=10
REL_ID="r1"
REL_KIND="LINKS"
REL_SOURCE="c1"
REL_TARGET="c2"
CONSTRAINT_KIND="non_negative"
CONSTRAINT_ENTITY="c1,c2"
CONSTRAINT_PROPERTY="value"
CTX_STEP=0
CTX_LABEL="end-to-end-witness"

# Transformations
T1_ENTITY="c1"
T1_OPERAND=3
T2_ENTITY="c2"
T2_OPERAND_FAIL=-12
T2_OPERAND_OK=-2

# Expected results after all transforms
EXPECTED_C1=8
EXPECTED_C2=8
EXPECTED_STEPS=2

echo "=============================================="
echo " SCR Canonical MLIR Generator"
echo "=============================================="
echo
echo "Source: semantic witness description (inline)"
echo "Definition: ${DEF_TYPE}"
echo "Entities: ${C1_ID}=${C1_INITIAL}, ${C2_ID}=${C2_INITIAL}"
echo "Transforms: ${T1_ENTITY}+${T1_OPERAND}, ${T2_ENTITY}${T2_OPERAND_FAIL}(fail), ${T2_ENTITY}${T2_OPERAND_OK}(ok)"
echo

# ============================================================
# Step 1: Generate MLIR from semantic description
# ============================================================

MLIR_FILE="$OUTPUT_DIR/canonical_counter_generated.mlir"

cat > "$MLIR_FILE" << 'MLIR_EOF'
/// Auto-generated from semantic witness description.
/// Source: semantic_kernel_canonical
/// Definition: ${DEF_TYPE}Definition
///
/// This file is generated by generate_canonical_mlir.sh,
/// not hand-authored.
///
/// Semantic Program:
///   Counter c1=${C1_INITIAL}, c2=${C2_INITIAL}
///   Transform c1: +3 (success, c1 → 8)
///   Transform c2: -12 (CONSTRAINT FAILURE, c2 unchanged at 10)
///   Transform c2: -2 (success, c2 → 8)
///   Observe c1 → 8, c2 → 8
///
/// Representation mapping:
///   Entity Instances → memref<1xi32> allocations
///   Constraints      → scf.if/else guards
///   Observations     → return values
MLIR_EOF

# Now append the actual MLIR body with variable substitution
cat >> "$MLIR_FILE" << MLIR_EOF

module attributes {
  scr.provenance = {
    source = "generated_from_semantic_witness",
    definition = "${DEF_TYPE}Definition",
    generation_method = "template_expansion",
    semantic_source = "test_end_to_end_witness"
  },
  scr.entity_definition = {
    type_id = "${DEF_TYPE}",
    value_schema = ["${DEF_PROPERTIES}"]
  },
  scr.entity_instance = [
    { entity_id = "${C1_ID}", definition_type = "${C1_TYPE}", initial_value = ${C1_INITIAL} : i32 },
    { entity_id = "${C2_ID}", definition_type = "${C2_TYPE}", initial_value = ${C2_INITIAL} : i32 }
  ],
  scr.relationship = {
    rel_id = "${REL_ID}",
    kind = "${REL_KIND}",
    source = "${REL_SOURCE}",
    target = "${REL_TARGET}"
  },
  scr.constraint = {
    kind = "${CONSTRAINT_KIND}",
    target_entity = "${CONSTRAINT_ENTITY}",
    target_property = "${CONSTRAINT_PROPERTY}"
  },
  scr.context = {
    initial_step = ${CTX_STEP} : index,
    label = "${CTX_LABEL}"
  }
} {
  func.func @end_to_end_witness() -> (i32, i32) attributes {
    scr.semantic_program = true
  } {
    // ---- c1 initial = ${C1_INITIAL} ----
    %c1_init = arith.constant ${C1_INITIAL} : i32
    %c1_state = memref.alloca() : memref<1xi32>
    %idx0 = arith.constant 0 : index
    memref.store %c1_init, %c1_state[%idx0] : memref<1xi32>

    // ---- c2 initial = ${C2_INITIAL} ----
    %c2_init = arith.constant ${C2_INITIAL} : i32
    %c2_state = memref.alloca() : memref<1xi32>
    memref.store %c2_init, %c2_state[%idx0] : memref<1xi32>

    // ---- Transform c1: +3 (success) ----
    %c3 = arith.constant ${T1_OPERAND} : i32
    %c1_v0 = memref.load %c1_state[%idx0] : memref<1xi32>
    %c1_v1 = arith.addi %c1_v0, %c3 : i32
    %c0 = arith.constant 0 : i32
    %cmp1 = arith.cmpi sge, %c1_v1, %c0 : i32
    scf.if %cmp1 {
      memref.store %c1_v1, %c1_state[%idx0] : memref<1xi32>
    } else {
      %c1_keep = memref.load %c1_state[%idx0] : memref<1xi32>
      memref.store %c1_keep, %c1_state[%idx0] : memref<1xi32>
    }

    // ---- Transform c2: -12 (CONSTRAINT FAILURE) ----
    %c_neg12 = arith.constant ${T2_OPERAND_FAIL} : i32
    %c2_v0 = memref.load %c2_state[%idx0] : memref<1xi32>
    %c2_v_fail = arith.addi %c2_v0, %c_neg12 : i32
    %cmp_fail = arith.cmpi sge, %c2_v_fail, %c0 : i32
    scf.if %cmp_fail {
      memref.store %c2_v_fail, %c2_state[%idx0] : memref<1xi32>
    } else {
      // Constraint violated: c2 unchanged
      %c2_keep = memref.load %c2_state[%idx0] : memref<1xi32>
      memref.store %c2_keep, %c2_state[%idx0] : memref<1xi32>
    }

    // ---- Transform c2: -2 (success) ----
    %c_neg2 = arith.constant ${T2_OPERAND_OK} : i32
    %c2_v1 = memref.load %c2_state[%idx0] : memref<1xi32>
    %c2_v2 = arith.addi %c2_v1, %c_neg2 : i32
    %cmp2 = arith.cmpi sge, %c2_v2, %c0 : i32
    scf.if %cmp2 {
      memref.store %c2_v2, %c2_state[%idx0] : memref<1xi32>
    } else {
      %c2_keep2 = memref.load %c2_state[%idx0] : memref<1xi32>
      memref.store %c2_keep2, %c2_state[%idx0] : memref<1xi32>
    }

    // ---- Observe c1 and c2 ----
    %r1 = memref.load %c1_state[%idx0] : memref<1xi32>
    %r2 = memref.load %c2_state[%idx0] : memref<1xi32>
    return %r1, %r2 : i32, i32
  }
}
MLIR_EOF

echo "[1/5] Generated: $MLIR_FILE"

# ============================================================
# Step 2: Verify generated file is non-empty and has key content
# ============================================================

if [ ! -s "$MLIR_FILE" ]; then
    echo "FAIL: Generated MLIR file is empty"
    exit 1
fi

for pattern in "module attributes" "func.func @end_to_end_witness" "memref.alloca" "arith.addi" "scf.if" "scr.provenance"; do
    if ! grep -q "$pattern" "$MLIR_FILE"; then
        echo "FAIL: Generated MLIR missing pattern: $pattern"
        exit 1
    fi
done

echo "[2/5] Content verification: PASS (all key patterns present)"

# ============================================================
# Step 3: Parse MLIR (if --verify or --full)
# ============================================================

if [ "$VERIFY" = true ] || [ "$FULL" = true ]; then
    echo "[3/5] Parsing MLIR..."
    if mlir-opt "$MLIR_FILE" --allow-unregistered-dialect > /dev/null 2>&1; then
        echo "      Parse: PASS"
    else
        echo "      Parse: FAIL"
        mlir-opt "$MLIR_FILE" --allow-unregistered-dialect 2>&1 | head -20
        exit 1
    fi
else
    echo "[3/5] Parsing MLIR... SKIPPED (use --verify or --full)"
fi

# ============================================================
# Step 4: Lower to LLVM (if --full)
# ============================================================

if [ "$FULL" = true ]; then
    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT

    echo "[4/5] Lowering to LLVM..."
    if mlir-opt "$MLIR_FILE" --allow-unregistered-dialect \
        --convert-scf-to-cf --convert-to-llvm \
        > "$TMP_DIR/lowered.mlir" 2>"$TMP_DIR/lower_err.txt"; then
        echo "      Lower: PASS"
    else
        echo "      Lower: FAIL"
        cat "$TMP_DIR/lower_err.txt"
        exit 1
    fi

    echo "      Translating to LLVM IR..."
    if mlir-translate --allow-unregistered-dialect "$TMP_DIR/lowered.mlir" \
        --mlir-to-llvmir > "$TMP_DIR/output.ll" 2>"$TMP_DIR/translate_err.txt"; then
        echo "      Translate: PASS"
    else
        echo "      Translate: FAIL"
        cat "$TMP_DIR/translate_err.txt"
        exit 1
    fi

    echo "      Compiling to object..."
    if llc -filetype=obj "$TMP_DIR/output.ll" -o "$TMP_DIR/output.o" 2>"$TMP_DIR/llc_err.txt"; then
        echo "      Compile: PASS"
    else
        echo "      Compile: FAIL"
        cat "$TMP_DIR/llc_err.txt"
        exit 1
    fi

    # C wrapper for execution
    cat > "$TMP_DIR/wrapper.c" << 'CEOF'
#include <stdio.h>
typedef struct { long long v1; long long v2; } Pair;
extern Pair end_to_end_witness(void);
int main(void) {
    Pair p = end_to_end_witness();
    printf("c1=%lld\n", p.v1);
    printf("c2=%lld\n", p.v2);
    return 0;
}
CEOF

    echo "      Linking and executing..."
    if gcc "$TMP_DIR/wrapper.c" "$TMP_DIR/output.o" \
        -o "$TMP_DIR/test_exec" 2>"$TMP_DIR/gcc_err.txt"; then
        OUTPUT=$("$TMP_DIR/test_exec" 2>&1)
        C1_VAL=$(echo "$OUTPUT" | grep "^c1=" | cut -d= -f2)
        C2_VAL=$(echo "$OUTPUT" | grep "^c2=" | cut -d= -f2)

        if [ "$C1_VAL" = "$EXPECTED_C1" ] && [ "$C2_VAL" = "$EXPECTED_C2" ]; then
            echo "      Execute: PASS (c1=$C1_VAL, c2=$C2_VAL)"
        else
            echo "      Execute: FAIL (expected c1=$EXPECTED_C1 c2=$EXPECTED_C2, got c1=$C1_VAL c2=$C2_VAL)"
            exit 1
        fi
    else
        echo "      Link: FAIL"
        cat "$TMP_DIR/gcc_err.txt"
        exit 1
    fi
else
    echo "[4/5] Lowering... SKIPPED (use --full)"
    echo "[5/5] Execution... SKIPPED (use --full)"
fi

echo
echo "=============================================="
echo " MLIR generation complete"
echo "=============================================="
echo
echo "Generated artifact: $MLIR_FILE"
echo "Provenance: derived from semantic witness description"
echo "Generation method: template_expansion"
echo
echo "To verify: $0 --verify"
echo "To execute: $0 --full"
