import { Reveal } from './Reveal'

const questions = [
  'How much CPU capacity is spent moving data?',
  'How much GPU capacity sits idle waiting for data?',
  'How much memory bandwidth is consumed by unnecessary copies?',
  'How much network traffic is generated by inefficient architectures?',
  'How much infrastructure exists merely to compensate for inefficient data movement?',
  'How much developer complexity comes from stitching together multiple messaging technologies?',
]

const propositions = [
  {
    title: 'More compute per rand',
    body: 'If less infrastructure work is spent moving and transforming messages, more of the budget goes to useful computation.',
  },
  {
    title: 'Better GPU economics',
    body: 'GPUs are expensive because they are extraordinarily capable. Keeping one waiting for data is therefore expensive.',
  },
  {
    title: 'Lower architectural complexity',
    body: 'A coherent family can replace separate messaging stacks for native apps, browsers, Kubernetes and GPU infrastructure.',
  },
  {
    title: 'Cloud-native operation',
    body: 'HyrxMQ is designed around Kubernetes rather than treating it as an afterthought — messaging that matches its deployment environment.',
  },
  {
    title: 'Open technology',
    body: 'Inspect, extend and integrate your infrastructure, and avoid unnecessary proprietary lock-in.',
  },
]

export function Benefits() {
  return (
    <section className="section" id="benefits">
      <div className="container">
        <div className="benefits__layout">
          <Reveal className="benefits__intro">
            <span className="eyebrow">Why Business Leaders Should Care</span>
            <h2 className="section__title">
              Infrastructure efficiency eventually becomes <span className="gradient-text">financial efficiency.</span>
            </h2>
            <p className="muted">
              If a business operates thousands of services, millions of messages, large data pipelines
              or expensive GPU infrastructure, the cost of moving data becomes material. The questions
              become economic:
            </p>
            <ul className="question-list">
              {questions.map((question, i) => (
                <li key={question}>
                  <span className="question-list__index">{String(i + 1).padStart(2, '0')}</span>
                  {question}
                </li>
              ))}
            </ul>
          </Reveal>

          <div className="benefits__cards">
            {propositions.map((item, i) => (
              <Reveal as="article" className="benefit-card" delay={i * 70} key={item.title}>
                <h3>{item.title}</h3>
                <p>{item.body}</p>
              </Reveal>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
