apiVersion: v1
kind: Service
metadata:
  name: hyrxmq-website
  namespace: hyrxmq-website
  labels:
    app.kubernetes.io/name: hyrxmq-website
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: hyrx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hyrxmq-website
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
