// Copyright 2026 Semantic Computational Runtime (SCR) Contributors
// SPDX-License-Identifier: Apache-2.0

//! # Topological Space
//!
//! Foundational representation of topological spaces as required by
//! `SCR-LIB-TOPOLOGY-POINTSET` and the normative `101_definition.md`.
//!
//! A topological space (X, τ) is the fundamental structure: a set with a
//! declared topology (collection of open sets satisfying the axioms).
//!
//! Per TOPOLOGY-RULE-001: topological meaning is normative.
//! Per TOPOLOGY-RULE-002: no representation is inherently authoritative.

use crate::error::{TopologyError, TopologyResult};

/// The kind of topology declared on a topological space.
///
/// The topology kind determines the neighbourhood semantics.
/// Per `TOPOLOGY-INV-001`: the declared topology MUST be respected.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum TopologyKind {
    /// Every subset is open. Maximally fine topology.
    Discrete,
    /// Only ∅ and X are open. Minimally coarse topology.
    Indiscrete,
    /// Open sets generated by metric balls.
    Metric,
    /// Subspace of another topological space.
    Subspace,
    /// Product of topological spaces.
    Product,
    /// Quotient by an equivalence relation.
    Quotient,
    /// Combinatorial topology (e.g. simplicial, cubical, CW complex).
    Combinatorial,
    /// User-declared custom topology.
    Custom(String),
}

impl std::fmt::Display for TopologyKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Discrete => write!(f, "Discrete"),
            Self::Indiscrete => write!(f, "Indiscrete"),
            Self::Metric => write!(f, "Metric"),
            Self::Subspace => write!(f, "Subspace"),
            Self::Product => write!(f, "Product"),
            Self::Quotient => write!(f, "Quotient"),
            Self::Combinatorial => write!(f, "Combinatorial"),
            Self::Custom(name) => write!(f, "Custom({})", name),
        }
    }
}

/// A topological space (X, τ) with a declared topology kind and element count.
///
/// This is a carrier structure representing topology semantics. The exact
/// encoding of open sets is implementation-defined per
/// `TOPOLOGY-INV-014` (Representation Independence).
#[derive(Debug, Clone, PartialEq)]
pub struct TopologicalSpace {
    /// Semantic identifier for this space.
    pub id: String,
    /// The declared kind of topology on this space.
    pub topology_kind: TopologyKind,
    /// Number of underlying elements (points/vertices/cells).
    pub element_count: usize,
    /// Human-readable description of the space.
    pub description: String,
}

impl TopologicalSpace {
    /// Creates a new topological space with a declared topology kind.
    ///
    /// Per `TOPOLOGY-INV-001`: the identity MUST be stable and non-empty.
    pub fn new(
        id: impl Into<String>,
        topology_kind: TopologyKind,
        element_count: usize,
        description: impl Into<String>,
    ) -> TopologyResult<Self> {
        let id = id.into();
        if id.trim().is_empty() {
            return Err(TopologyError::InvariantViolation(
                "TOPOLOGY-INV-001: Topological space identity cannot be empty".to_string(),
            ));
        }
        Ok(Self {
            id,
            topology_kind,
            element_count,
            description: description.into(),
        })
    }

    /// Returns the declared topology kind.
    pub fn topology_kind(&self) -> &TopologyKind {
        &self.topology_kind
    }

    /// Returns whether this space is declared as using a metric topology.
    ///
    /// Per `TOPOLOGY-RULE-003`: metric MUST NOT be assumed if not declared.
    pub fn has_metric(&self) -> bool {
        matches!(self.topology_kind, TopologyKind::Metric)
    }

    /// Returns whether this is a combinatorial topology (complex-based).
    pub fn is_combinatorial(&self) -> bool {
        matches!(self.topology_kind, TopologyKind::Combinatorial)
    }
}
