apiVersion: v1
kind: Service
metadata:
  name: hyrxmq
  namespace: hyrxmq
  labels:
    app.kubernetes.io/name: hyrxmq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hyrxmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: web
      port: 8080
      targetPort: web
      protocol: TCP
